// wap/src/components/AnnouncementCenter.tsx
import React from 'react'
import { Bell, X } from 'lucide-react'

import { listPublicAnnouncements, type Announcement } from '@/api/announcement'
import { Button } from '@/components/ui/button'
import { cn } from '@/lib/utils'

interface Props {
  active: boolean
}

const READ_KEY = 'gpt2api.announcement.read.ids'

function readIDs(): number[] {
  try {
    const parsed = JSON.parse(localStorage.getItem(READ_KEY) || '[]')
    if (Array.isArray(parsed)) {
      return parsed.map((id) => Number(id)).filter((id) => Number.isFinite(id) && id > 0)
    }
  } catch {
    return []
  }
  return []
}

function writeIDs(ids: number[]) {
  const uniq = Array.from(new Set(ids.filter((id) => Number.isFinite(id) && id > 0)))
  localStorage.setItem(READ_KEY, JSON.stringify(uniq))
}

export default function AnnouncementCenter({ active }: Props) {
  const [items, setItems] = React.useState<Announcement[]>([])
  const [loaded, setLoaded] = React.useState(false)
  const [loading, setLoading] = React.useState(false)
  const [popupOpen, setPopupOpen] = React.useState(false)
  const [listOpen, setListOpen] = React.useState(false)
  const [current, setCurrent] = React.useState<Announcement | null>(null)

  const load = React.useCallback(async () => {
    if (!active || loading || loaded) return
    setLoading(true)
    try {
      const data = await listPublicAnnouncements()
      const nextItems = data.items || []
      setItems(nextItems)
      setLoaded(true)
      const read = new Set(readIDs())
      const firstUnread = nextItems.find((item) => !read.has(item.id))
      if (firstUnread) {
        setCurrent(firstUnread)
        setPopupOpen(true)
      }
    } finally {
      setLoading(false)
    }
  }, [active, loaded, loading])

  React.useEffect(() => {
    void load()
  }, [load])

  const acknowledge = () => {
    if (current) {
      writeIDs([...readIDs(), current.id])
    }
    setPopupOpen(false)
  }

  const openList = () => {
    setListOpen(true)
    void load()
  }

  if (!active) return null

  return (
    <>
      <Button
        type="button"
        variant="secondary"
        size="sm"
        onClick={openList}
        className="h-9 rounded-full border border-border/60 bg-secondary/70 px-3 shadow-sm"
      >
        <Bell className="h-4 w-4" />
        公告
      </Button>

      {popupOpen && current && (
        <AnnouncementDialog title={current.title} onClose={() => setPopupOpen(false)}>
          <div className="max-h-[55vh] overflow-y-auto whitespace-pre-wrap break-words text-sm leading-7 text-muted-foreground">
            {current.content}
          </div>
          <div className="mt-5 flex gap-2">
            <Button variant="outline" className="h-10 flex-1 rounded-2xl" onClick={() => setListOpen(true)}>
              公告列表
            </Button>
            <Button className="h-10 flex-1 rounded-2xl" onClick={acknowledge}>
              知道了
            </Button>
          </div>
        </AnnouncementDialog>
      )}

      {listOpen && (
        <AnnouncementDialog title="公告列表" onClose={() => setListOpen(false)}>
          <div className={cn('max-h-[62vh] space-y-3 overflow-y-auto', loading && 'opacity-60')}>
            {items.length === 0 && (
              <div className="rounded-2xl border border-dashed border-border p-8 text-center text-sm text-muted-foreground">
                暂无公告
              </div>
            )}
            {items.map((item) => (
              <article key={item.id} className="rounded-2xl border border-border/70 bg-secondary/30 p-4">
                <h3 className="text-sm font-bold leading-6">{item.title}</h3>
                <p className="mt-2 whitespace-pre-wrap break-words text-sm leading-7 text-muted-foreground">
                  {item.content}
                </p>
              </article>
            ))}
          </div>
        </AnnouncementDialog>
      )}
    </>
  )
}

function AnnouncementDialog({
  title,
  children,
  onClose,
}: {
  title: string
  children: React.ReactNode
  onClose: () => void
}) {
  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/35 px-4 backdrop-blur-sm">
      <section className="w-full max-w-sm rounded-[28px] border border-border/70 bg-background p-5 text-foreground shadow-2xl">
        <div className="mb-4 flex items-center justify-between gap-3">
          <h2 className="text-lg font-black tracking-tight">{title}</h2>
          <Button type="button" variant="ghost" size="icon-sm" aria-label="关闭" onClick={onClose}>
            <X className="h-4 w-4" />
          </Button>
        </div>
        {children}
      </section>
    </div>
  )
}

// web/src/components/AnnouncementCenter.vue
<script setup lang="ts">
import { computed, onMounted, ref, watch } from 'vue'
import { ElMessage } from 'element-plus'
import { listPublicAnnouncements, type Announcement } from '@/api/announcement'

const props = withDefaults(defineProps<{ active?: boolean }>(), { active: true })

const READ_KEY = 'gpt2api.announcement.read.ids'

const rows = ref<Announcement[]>([])
const loading = ref(false)
const loaded = ref(false)
const dialogVisible = ref(false)
const listVisible = ref(false)
const current = ref<Announcement | null>(null)

const hasItems = computed(() => rows.value.length > 0)

function readIDs(): number[] {
  try {
    const parsed = JSON.parse(localStorage.getItem(READ_KEY) || '[]')
    if (Array.isArray(parsed)) {
      return parsed.map((id) => Number(id)).filter((id) => Number.isFinite(id) && id > 0)
    }
  } catch {
    return []
  }
  return []
}

function writeIDs(ids: number[]) {
  const uniq = Array.from(new Set(ids.filter((id) => Number.isFinite(id) && id > 0)))
  localStorage.setItem(READ_KEY, JSON.stringify(uniq))
}

function markRead(id: number) {
  writeIDs([...readIDs(), id])
}

async function load() {
  if (!props.active || loading.value || loaded.value) return
  loading.value = true
  try {
    const data = await listPublicAnnouncements()
    rows.value = data.items || []
    loaded.value = true
    const read = new Set(readIDs())
    const firstUnread = rows.value.find((item) => !read.has(item.id))
    if (firstUnread) {
      current.value = firstUnread
      dialogVisible.value = true
    }
  } catch {
    ElMessage.error('公告加载失败')
  } finally {
    loading.value = false
  }
}

function acknowledge() {
  if (current.value) markRead(current.value.id)
  dialogVisible.value = false
}

function openList() {
  listVisible.value = true
  load()
}

watch(() => props.active, (active) => {
  if (active) load()
})

onMounted(load)
</script>

<template>
  <div v-if="active" class="announcement-center">
    <el-button link class="announcement-entry" :loading="loading" @click="openList">
      <el-icon><Bell /></el-icon>
      <span>公告</span>
    </el-button>

    <el-dialog v-model="dialogVisible" title="公告" width="520px" append-to-body>
      <div v-if="current" class="announcement-popup">
        <h3>{{ current.title }}</h3>
        <div class="announcement-content">{{ current.content }}</div>
      </div>
      <template #footer>
        <el-button @click="listVisible = true">公告列表</el-button>
        <el-button type="primary" @click="acknowledge">知道了</el-button>
      </template>
    </el-dialog>

    <el-dialog v-model="listVisible" title="公告列表" width="680px" append-to-body>
      <el-empty v-if="!loading && !hasItems" description="暂无公告" />
      <div v-else v-loading="loading" class="announcement-list">
        <el-card v-for="item in rows" :key="item.id" shadow="never" class="announcement-card">
          <template #header>
            <div class="announcement-card-head">
              <strong>{{ item.title }}</strong>
              <el-tag size="small" type="info">#{{ item.id }}</el-tag>
            </div>
          </template>
          <div class="announcement-content">{{ item.content }}</div>
        </el-card>
      </div>
    </el-dialog>
  </div>
</template>

<style scoped lang="scss">
.announcement-entry {
  display: inline-flex;
  align-items: center;
  gap: 4px;
  min-height: 36px;
}

.announcement-popup h3 {
  margin: 0 0 12px;
  font-size: 18px;
  line-height: 1.4;
}

.announcement-content {
  white-space: pre-wrap;
  word-break: break-word;
  color: var(--el-text-color-regular);
  line-height: 1.7;
}

.announcement-list {
  display: grid;
  gap: 12px;
  min-height: 120px;
}

.announcement-card-head {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 12px;
}
</style>
